### ISSUE TITLE
create frontend design

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/ruhacks-tasks#2]
__Note__: this is dependent on task #1, so if migration occurs then you may need to wait until after migration finishes to begin a draft.

However, you can begin by creating up a design anyways and that way there will be something to show for next meeting.

**Comment by ktsuench** [comment]
# Compiling Pug to HTML

## Option 1
You can refer to this (doc)[https://pugjs.org/api/reference.html] for compiling the pug files to html if you would prefer working in html instead. This requires that you create a nodejs script and running it.

## Option 2
If you don't want to write and run a nodejs script, you can try the (cli)[https://github.com/pugjs/pug-cli] instead.

**Comment by ktsuench** [comment]
Also, if possible try and post a screenshot every week or so to show progress and get some feedback :)

**Comment by streacy** [comment]
So far this is the front end for when people sign up for the hackathon. Let me know if I should add/remove or change anything 


![screen shot 2017-11-13 at 7 55 37 pm](https://user-images.githubusercontent.com/25357722/32757329-019f5366-c8ad-11e7-9dd4-a2eeb01e25fd.png)

![screen shot 2017-11-13 at 7 56 21 pm](https://user-images.githubusercontent.com/25357722/32757334-055632f4-c8ad-11e7-9076-514f83152b15.png)

**Comment by jas2996** [comment]
@streacy 
The faq looks a bit crowded. I was thinking of using a cards and then using a 3d "animation" to flip the card. The front of the card has the faq and the back would have the answer.

See example: https://desandro.github.io/3dtransforms/docs/card-flip.html.

I quickly threw some code together as another example:

```
<!DOCTYPE html>
<html lang="en">
<head>
<style type="text/css">
    .flip-container {
        margin: 50px;
        perspective: 1000;
        display: inline-block;
    }
    .flip-container:hover .card {
        transform: rotateY(180deg);
		cursor: pointer;
    }
    .card, .front, .back {
        width: 130px;
        height: 195px;
    }
    .card {
        transition: 0.5s;
        transform-style: preserve-3d;
        position: relative;
    }
    .front, .back {
        backface-visibility: hidden;
        position: absolute;
    }
    .front {
        z-index: 1;
        transform: rotateY(180deg);
    }
    .back {
        z-index: 2;
        transform: rotateY(0deg);
    }
</style>
</head>
<body>
    <div class="flip-container">
        <div class="card">
            <div class="front">
                <p>This is my answer<p>
            </div>
            <div class="back">
                <p>This is my question<p>
            </div>
        </div>
    </div>
</body>
</html> 
```

@ktsuench thoughts?

**Comment by streacy** [comment]
I try that tonight and send screen shots of what it looks like

**Comment by ktsuench** [comment]
@jas2996 I think that sounds interesting but in terms of UX it might be a hassle since they would have hover over them. Plus that might not be an obvious interaction unless stated.

I think keeping with something simple would be better. In terms of a css framework I would suggest trying out [bulma](https://bulma.io/). You can try out using the [tile layout](https://bulma.io/documentation/layout/tiles/) for the FAQ or set them up as [cards](https://bulma.io/documentation/components/card/).

@streacy  if you think you are comfortable with using the bulma framework then I'll modify some of the variables (color-wise and font-wise) to suit our needs. Or if you find a css library or framework that you're comfortable with, comment with a link and I'll compile the code with the RU Hack specific changes.

**Comment by ktsuench** [comment]
@streacy I saw your slack msg. I'll look into compiling the source code of Bulma with our colors and fonts.

### Tasks
- [ ] Compile source of Bulma with RU Hacks color scheme and fonts
- [ ] Compile pug source to HTML? @streacy check this off if you've got it done and don't have any issues
- [ ] @streacy create a new frontend repo for 2018 website under our org (name: 2018-website-frontend)

**Comment by ktsuench** [comment]
@streacy I've got the pug source compiled to html and the Bulma css library is compiled as well. The pug compiled html source is under the [archive branch](https://github.com/ruhacks/ruhacks-2018-website-frontend/tree/archive) and the _new_ website is under the [master branch](https://github.com/ruhacks/ruhacks-2018-website-frontend). Try and come up with your own design using the original design as a reference as well looking at other websites for inspiration.

Some examples include [Unchain](http://www.unchain.org/) (_Jas likes the slant on the homepage_), [UI Parade](http://www.uiparade.com/) (_there are some interesting designs here_), [Webdesigner Depot](https://www.webdesignerdepot.com/) (_they have some good tutorials and examples to look through_), and [Codrops](https://tympanus.net/codrops/) (_they're like Webdesigner Depot_).

If you need some help or suggestions reach out to me or @jas2996 for some inspirations.

**Comment by streacy** [comment]
I started from scratch on the template under the master branch and heres what I have for now. I still have to change the fonts and add the Ryerson colour schemes
![screen shot 2017-11-22 at 10 50 52 pm](https://user-images.githubusercontent.com/25357722/33159051-8fb41416-cfdd-11e7-9e5e-fbfcef6f61fe.png)

![screen shot 2017-11-22 at 11 30 39 pm](https://user-images.githubusercontent.com/25357722/33159053-92a4b338-cfdd-11e7-84bb-bc0b391b6ca7.png)

![screen shot 2017-11-22 at 11 30 51 pm](https://user-images.githubusercontent.com/25357722/33159057-988fae24-cfdd-11e7-9aa0-bfff47fa72e0.png)

**Comment by ktsuench** [comment]
You won't have to change the fonts. The default font is the 'Ubuntu' font we've been using on the old site. Also, I feel like using cards might not have been a good idea (_that's what it seems like your using for the faq_). It probably would look better using tiles since it'll be using the flex box model. _In other words, tiles that don't have enough content won't be cut short like the "Who can attend?" card in the screenshot_.

Also, below is a reference of colors we should be using on the site. I've commented which ones have replaced the Bulma css defaults. Try and stick with these colors.
```
// Primary Palette

@ryerson-blue:  #004c9b; // primary
@ryerson-gold:  #ffdc00; // warning
@black:         #000000;
@white:         #ffffff;

// Secondary Palette
// From darkest to lightest

@blue-midnight:     #002d72;
@blue-lochmara:     #0077c8; // link
@blue-cerulean:     #00a9ef; // info
@blue-malibu:       #5bc2f4;
@orange-web:        #ffa300;
@yellow-supernova:  #ffc609;
@yellow-turbo:      #ffee00;
@gray-dusty:        #999999;
@gray-alto:         #d9d9d9;

// Tertiary Palette

@orange-blaze:          #ff7200;
@red-ribbon:            #e40032; // danger
@red-rose:              #eb0072;
@purple-seance:         #792082;
@blue-marguerite:       #7474c1;
@yellow-buddha-gold:    #bfbe00;
@green-haze:            #009a44; // success
@blue-bondi:            #00a3ad;
@blue-tradewind:        #6bbfae;
```

**Comment by streacy** [comment]
Here it is with tiles but I kept the About section with cards 
![screen shot 2017-11-23 at 12 33 20 am](https://user-images.githubusercontent.com/25357722/33159930-33d302c0-cfe6-11e7-94b3-8013636839f9.png)

![screen shot 2017-11-23 at 12 33 40 am](https://user-images.githubusercontent.com/25357722/33159931-35e83c1a-cfe6-11e7-9ca2-d71fdf64bb31.png)

**Comment by ktsuench** [comment]
Alright looks good, maybe we can differentiate the tile background from the section background and that'll make it stand out some more. Keep up the good work! 👍 :)

**Comment by jas2996** [comment]
@streacy looks good! I know I said to use the cards but I agree with Ken's point now that I see it lol

**Comment by streacy** [comment]
I changed it up a bit 
![screen shot 2017-11-25 at 8 15 22 pm](https://user-images.githubusercontent.com/25357722/33236309-6b82d0ae-d21d-11e7-946b-6be4f0c8732c.png)
![screen shot 2017-11-25 at 8 06 34 pm](https://user-images.githubusercontent.com/25357722/33236310-6b911e48-d21d-11e7-943f-199b4c69221a.png)
![screen shot 2017-11-25 at 8 06 13 pm](https://user-images.githubusercontent.com/25357722/33236311-6ba746aa-d21d-11e7-9c2d-4c3ffe8b299d.png)

Let me know what I should change

**Comment by ktsuench** [comment]
# Updated Splash background
## New Splash Background
Updated the splash image with a new one:
![slanted_800x450](https://user-images.githubusercontent.com/6343135/33237317-09f04292-d23e-11e7-8d74-2552c539e4e8.png)
## What it looks like on site
The changes have been made to the `index.html` file
![ss](https://user-images.githubusercontent.com/6343135/33237327-56ab8380-d23e-11e7-8ae8-e650c4955677.png)

**Comment by ktsuench** [comment]
# Updates
Released to production now. 

___Please do not make changes to the master branch of the repo. Instead make them on the dev branch instead.___

## Notes
- Added in [Open Graph](https://developers.facebook.com/tools/debug/sharing/?q=ruhacks.com) and [Twitter Card](https://cards-dev.twitter.com/validator) images and info.
- Added new domain [2018.ruhacks.com](https://2018.ruhacks.com) so when we update site again OG and Twitter Cards images don't break.
- [www.ruhacks.com](https://www.ruhacks.com) redirects to [2018.ruhacks.com](https://2018.ruhacks.com) now

**Comment by ktsuench** [comment]
@streacy please add in the missing js scripts ASAP. Navigation on mobile does not work right now.

**Comment by ktsuench** [comment]
Closing this issue. All further issues related to frontend should be opened in ruhacks/ruhacks-2018-website-frontend repo.
